### ISSUE TITLE
Where's the Docs?

### ISSUE THREAD

**Issue by DrAlta** [open-spaced-repetition/rs-fsrs#11]
How does one use this? There is no documentation and no comments.  I tried looking at the other implementation of FSRS but they are all in the same state.

**Comment by L-M-Sherlock** [comment]
The ts-fsrs package has a detailed documentation: https://github.com/open-spaced-repetition/ts-fsrs?tab=readme-ov-file#basic-use

**Comment by DrAlta** [comment]
```
3. Scheduling with FSRS:
The core functionality lies in the fsrs function. When invoked, it returns a collection of cards scheduled based on different potential user ratings:```

code uses the `FSRS()` function instead of `fsrs()`

**Comment by L-M-Sherlock** [comment]
Because ts-fsrs has fsrs function:

```typescript
export const fsrs = (params?: Partial<FSRSParameters>) => {
  return new FSRS(params || {});
};
```

https://github.com/open-spaced-repetition/ts-fsrs/blob/55b0a1eb8e95b3df1995bb97b3796b030abfb850/src/fsrs/fsrs.ts#L430-L432
