### ISSUE TITLE
keep up with go version

### ISSUE THREAD

**Issue by asukaminato0721** [open-spaced-repetition/rs-fsrs#22]
https://github.com/open-spaced-repetition/go-fsrs

currently meet this <https://github.com/open-spaced-repetition/go-fsrs/pull/23>.

**Comment by asukaminato0721** [comment]
well, since now we have llm, why not just totally rewrite, just keep the origin public api

**Comment by asukaminato0721** [comment]
maybe something like `cat *.go > ` then directly give to the llm could made it.

**Comment by asukaminato0721** [comment]
https://github.com/open-spaced-repetition/go-fsrs/pull/13 current progress.

**Comment by asukaminato0721** [comment]
@L-M-Sherlock any idea?

**Comment by L-M-Sherlock** [comment]
busy on https://github.com/open-spaced-repetition/py-fsrs/pull/62

To keep up with go-fsrs, I will ask LLM to port the latest code if nobody helps it.

**Comment by asukaminato0721** [comment]
some may helpful code

<https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=31856d81822bb57f60b6d0617b938c71>

**Comment by asukaminato0721** [comment]
For memo <https://gitlab.com/antonok/enum_dispatch>

For this crate, performance is not important. `Box<dyn >` is acceptable.
