### ISSUE TITLE
rs-fsrs -> fsrs-rs? fsrs-scheduler-rs?

### ISSUE THREAD

**Issue by dae** [open-spaced-repetition/rs-fsrs#6]
Again, a very minor suggestion - the "-rs" part is usually trailing. Another option would be fsrs-scheduler or fsrs-scheduler-rs, which would better distinguish it from fsrs-optimizer-rs - WDYT?

**Comment by dae** [comment]
On second thought, if you intend to implement online learning in the future, perhaps this code should be merged into fsrs-optimizer-rs, and then we should rename that to fsrs-rs. What do you think @L-M-Sherlock? I can handle the merging if you want to go down that route.

**Comment by L-M-Sherlock** [comment]
I'm considering it. The main point bothering me is rs-fsrs has its own short-term schedule, but Anki has learning steps. In fsrs4anki scheduler, it custom scheduling doesn't modify the short-term schedule. Maybe we need develop a independent module for the integration.

**Comment by L-M-Sherlock** [comment]
And there are two method to generate the new interval.

1. Update the stability stored in custom data based on itself and the latest rating and elapsed days.
2. Recalculate the stability from entire review history of the card (including the latest review)

Method 1 needs less calculation but it would be inaccurate when users update their weights.

Method 2 needs more calculation but it is more accurate.

**Comment by dae** [comment]
For the second method, my main concern would be whether the processing time is fast enough. For example, if it takes 10ms that's easy to justify; if it starts growing into the 100ms+ range, that may start to impact the perceived speed of review, and start impacting battery drain. I guess we'd need to do some benchmarks to get an idea of how a card with 10 previous reviews, and maybe 50 previous reviews would perform.

**Comment by dae** [comment]
> The main point bothering me is rs-fsrs has its own short-term schedule
> Maybe we need develop a independent module for the integration.

Ah, I see. That would work too, and might even be preferable, as I'd like to refactor the current API. I do think it probably makes sense to put the review code in the same crate as the optimizer though, as the two work together and it would be easier to maintain.

**Comment by L-M-Sherlock** [comment]
Me too. I prefer to continue the development in https://github.com/open-spaced-repetition/fsrs-optimizer-rs

And the method 1 and method 2 are not mutually exclusive. We can develop two methods both.

**Comment by dae** [comment]
Just saw your reddit post; congrats on the 1 year anniversary :-)

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs-optimizer-rs/pull/58
